language: php
php:
- 5.6
- 7.1
- 7.2
before_install:
- composer self-update
before_script:
- composer install
script:
- if [[ $PHPSTAN = 1 ]]; then composer require --dev "phpstan/phpstan:^0.10" && vendor/bin/phpstan analyse -c phpstan.neon -l 0 --memory-limit=1G src; fi
- phpunit --configuration phpunit.xml
matrix:
- php: 7.1
  env: PHPSTAN=1